<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "w_misc"
 *
 * Auto generated by Extension Builder 2016-09-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WTP - misc',
	'description' => 'For now its main function is attaching INSTANCE_CONTEXT info into backend system toolbar.',
	'category' => 'misc',
	'author' => 'A. wolo Wolski / wolo.pl \'.\' studio',
	'author_email' => 'wolo.wolski@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.00-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
